# Generated by Django 5.1.1 on 2024-12-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_slider_highlighted_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='points',
            field=models.TextField(default='Default'),
        ),
    ]
