# Generated by Django 5.1.1 on 2024-12-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_why_choose_us_delete_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='why_choose_us',
            name='image',
            field=models.ImageField(upload_to='why_choose_us/'),
        ),
    ]
